import { supabase } from '../lib/supabase';
import { subscribeToPostgresChanges } from '../lib/realtime';
import type { ScheduleItem } from '../types';
export const mapSchedule=(r:any):ScheduleItem=>({id:r.id,day:r.day,startTime:r.start_time,endTime:r.end_time,subject:r.subject||'',teacher:r.teacher||undefined,type:r.type,active:r.active,createdAt:r.created_at,updatedAt:r.updated_at});
export async function loadSchedule(all=false){let q=supabase.from('schedule').select('*').order('day_order').order('start_time');if(!all)q=q.eq('active',true);const {data,error}=await q;if(error)throw error;return (data||[]).map(mapSchedule)}
export function subscribeSchedule(cb:(items:ScheduleItem[])=>void,onError?:(e:unknown)=>void){let mounted=true;const fetch=async()=>{try{const d=await loadSchedule();if(mounted)cb(d)}catch(e){onError?.(e)}};void fetch();const unsubscribe=subscribeToPostgresChanges({topic:'schedule',table:'schedule',onChange:()=>void fetch(),onError});return()=>{mounted=false;unsubscribe()}}
export function subscribeAllSchedule(cb:(items:ScheduleItem[])=>void,onError?:(e:unknown)=>void){let mounted=true;const fetch=async()=>{try{const d=await loadSchedule(true);if(mounted)cb(d)}catch(e){onError?.(e)}};void fetch();const unsubscribe=subscribeToPostgresChanges({topic:'schedule-admin',table:'schedule',onChange:()=>void fetch(),onError});return()=>{mounted=false;unsubscribe()}}
export async function createSchedule(d:Omit<ScheduleItem,'id'|'createdAt'|'updatedAt'>){const {data,error}=await supabase.from('schedule').insert({day:d.day,day_order:['Senin','Selasa','Rabu','Kamis','Jumat'].indexOf(d.day),start_time:d.startTime,end_time:d.endTime,subject:d.subject,teacher:d.teacher,type:d.type,active:d.active}).select('id').single();if(error)throw error;return data}
export async function updateSchedule(id:string,d:Partial<ScheduleItem>){const x:any={};if(d.day){x.day=d.day;x.day_order=['Senin','Selasa','Rabu','Kamis','Jumat'].indexOf(d.day)}if(d.startTime)x.start_time=d.startTime;if(d.endTime)x.end_time=d.endTime;if(d.subject!==undefined)x.subject=d.subject;if(d.teacher!==undefined)x.teacher=d.teacher;if(d.type)x.type=d.type;if(d.active!==undefined)x.active=d.active;const {error}=await supabase.from('schedule').update(x).eq('id',id);if(error)throw error}
export async function deleteSchedule(id:string){const {error}=await supabase.from('schedule').delete().eq('id',id);if(error)throw error}
