import { supabase } from '../lib/supabase';
import { subscribeToPostgresChanges } from '../lib/realtime';
import { trackEvent } from '../lib/analytics';
import type { Priority,Task,TaskStatus } from '../types';
export const mapTask=(r:any):Task=>({id:r.id,title:r.title,description:r.description||'',subjectId:r.subject_id,subjectName:r.subject_name,teacherName:r.teacher_name||'',createdBy:r.created_by,createdByName:r.created_by_name||'',assignedTo:r.assigned_to,dueDate:r.due_date,dueTime:String(r.due_time).slice(0,5),dueAt:r.due_at,status:r.status,priority:r.priority,fileUrl:r.file_url||undefined,fileName:r.file_name||undefined,fileType:r.file_type||undefined,fileSize:r.file_size||undefined,storagePath:r.storage_path||undefined,createdAt:r.created_at,updatedAt:r.updated_at,completedAt:r.completed_at,submissionStatus:r.submission_status,notes:r.notes||undefined});
function cols(){return 'id,title,description,subject_id,subject_name,teacher_name,created_by,created_by_name,assigned_to,due_date,due_time,due_at,status,priority,file_url,file_name,file_type,file_size,storage_path,created_at,updated_at,completed_at,submission_status,notes'}
export async function loadTasks(ownUid?:string){let q=supabase.from('tasks').select(cols()).order('due_date',{ascending:true}).order('due_time',{ascending:true});if(ownUid)q=q.eq('assigned_to',ownUid);const {data,error}=await q;if(error)throw error;const tasks=(data||[]).map(mapTask);return Promise.all(tasks.map(async t=>{if(t.storagePath){const {data:signed}=await supabase.storage.from('task-files').createSignedUrl(t.storagePath,3600);if(signed?.signedUrl)t.fileUrl=signed.signedUrl;}return t}))}
export async function getTask(id:string){const {data,error}=await supabase.from('tasks').select(cols()).eq('id',id).maybeSingle();if(error)throw error;if(!data)return null;let t=mapTask(data);if(t.storagePath){const {data:signed}=await supabase.storage.from('task-files').createSignedUrl(t.storagePath,3600);if(signed?.signedUrl)t.fileUrl=signed.signedUrl;}return t}
export function subscribeUserTasks(uid:string,cb:(tasks:Task[])=>void,onError?:(e:unknown)=>void){let mounted=true;const fetch=async()=>{try{const d=await loadTasks(uid);if(mounted)cb(d)}catch(e){onError?.(e)}};void fetch();const unsubscribe=subscribeToPostgresChanges({topic:`tasks-user:${uid}`,table:'tasks',filter:`assigned_to=eq.${uid}`,onChange:()=>void fetch(),onError});return()=>{mounted=false;unsubscribe()}}
export function subscribeAllTasks(cb:(tasks:Task[])=>void,onError?:(e:unknown)=>void){let mounted=true;const fetch=async()=>{try{const d=await loadTasks();if(mounted)cb(d)}catch(e){onError?.(e)}};void fetch();const unsubscribe=subscribeToPostgresChanges({topic:'tasks-all',table:'tasks',onChange:()=>void fetch(),onError});return()=>{mounted=false;unsubscribe()}}
export async function createTask(data:Record<string,any>){const {data:row,error}=await supabase.from('tasks').insert({title:data.title,description:data.description||'',subject_id:data.subjectId,subject_name:data.subjectName,teacher_name:data.teacherName,created_by:data.createdBy,created_by_name:data.createdByName,assigned_to:data.assignedTo,due_date:data.dueDate,due_time:data.dueTime,due_at:data.dueAt,status:data.status,priority:data.priority,file_url:data.fileUrl||null,file_name:data.fileName||null,file_type:data.fileType||null,file_size:data.fileSize||null,storage_path:data.storagePath||null,submission_status:data.submissionStatus||'not_submitted',notes:data.notes||null}).select('id').single();if(error)throw error;await trackEvent('task_created');return row}
export async function updateTask(id:string,data:Record<string,any>){const mapped:any={...data};if(data.subjectId!==undefined){mapped.subject_id=data.subjectId;delete mapped.subjectId}if(data.subjectName!==undefined){mapped.subject_name=data.subjectName;delete mapped.subjectName}if(data.teacherName!==undefined){mapped.teacher_name=data.teacherName;delete mapped.teacherName}if(data.assignedTo!==undefined){mapped.assigned_to=data.assignedTo;delete mapped.assignedTo}if(data.createdBy!==undefined){mapped.created_by=data.createdBy;delete mapped.createdBy}if(data.createdByName!==undefined){mapped.created_by_name=data.createdByName;delete mapped.createdByName}for(const [a,b] of [['dueDate','due_date'],['dueTime','due_time'],['dueAt','due_at'],['fileUrl','file_url'],['fileName','file_name'],['fileType','file_type'],['fileSize','file_size'],['storagePath','storage_path'],['submissionStatus','submission_status'],['completedAt','completed_at']] as const){if(a in mapped){mapped[b]=mapped[a];delete mapped[a]}}const {error}=await supabase.from('tasks').update(mapped).eq('id',id);if(error)throw error}
export async function removeTask(id:string){const {data,error}=await supabase.from('tasks').select('storage_path').eq('id',id).maybeSingle();if(error)throw error;const path=data?.storage_path as string|undefined;const {error:delError}=await supabase.from('tasks').delete().eq('id',id);if(delError)throw delError;if(path){const {error:fileError}=await supabase.storage.from('task-files').remove([path]);if(fileError)throw fileError}}
export async function completeTask(id:string){await updateTask(id,{status:'completed' as TaskStatus,completedAt:new Date().toISOString()});await trackEvent('task_completed')}
export const taskStatusOptions:TaskStatus[]=['pending','in_progress','submitted','completed','overdue'];export const priorityOptions:Priority[]=['low','medium','high','urgent'];
