import { useEffect, useState } from 'react';
import { Activity, Globe2, ShieldCheck, Smartphone } from 'lucide-react';
import Card from '../components/ui/Card';
import EmptyState from '../components/ui/EmptyState';
import Skeleton from '../components/ui/Skeleton';
import { useAuth } from '../context/AuthContext';
import { supabase } from '../lib/supabase';
import { formatDateTime, errorMessage } from '../lib/utils';

type ActivityRow={id:string;event_type:string;device_type:string|null;device_name:string|null;manufacturer:string|null;device_model:string|null;os:string|null;os_version:string|null;browser:string|null;browser_version:string|null;ip_address:string|null;client_timezone:string|null;created_at:string};

export default function ActivityCenter(){const {user}=useAuth();const [rows,setRows]=useState<ActivityRow[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{let alive=true;const load=async()=>{setLoading(true);setError(''); if(!user?.id){setRows([]);setLoading(false);return;} const {data,error:e}=await supabase.from('login_activity').select('id,event_type,device_type,device_name,manufacturer,device_model,os,os_version,browser,browser_version,ip_address,client_timezone,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100);if(!alive)return;if(e){setError(errorMessage(e));setRows([]);}else setRows((data??[]) as unknown as ActivityRow[]);setLoading(false);};void load();return()=>{alive=false}},[user?.id]);
 return <div className="mx-auto w-full max-w-6xl space-y-5 pb-8 fade-up"><header><div className="inline-flex items-center gap-2 rounded-full bg-indigo-50 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.16em] text-indigo-700 dark:bg-indigo-950/40 dark:text-indigo-300"><Activity size={12}/>Security Activity</div><h1 className="mt-3 text-3xl font-black tracking-tight">Aktivitas & Perangkat</h1><p className="mt-2 text-sm text-slate-500">Riwayat keamanan akun dan perangkat yang terdeteksi.</p></header>{error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}{loading?<div className="space-y-3">{[1,2,3,4].map(i=><Skeleton key={i} className="h-24 rounded-2xl"/>)}</div>:rows.length===0?<Card className="p-6"><EmptyState title="Belum ada aktivitas" description="Aktivitas keamanan akan muncul setelah login atau perubahan sesi."/></Card>:<div className="space-y-3">{rows.map(row=><Card key={row.id} className="p-4"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-indigo-50 text-indigo-600 dark:bg-indigo-950/40 dark:text-indigo-300"><ShieldCheck size={18}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><div className="text-sm font-black">{row.event_type}</div><span className="text-[10px] text-slate-400">{formatDateTime(row.created_at)}</span></div><div className="mt-2 grid gap-2 text-xs text-slate-500 sm:grid-cols-2 lg:grid-cols-3"><span><Smartphone size={13} className="mr-1 inline"/>{[row.manufacturer,row.device_model,row.device_name].filter(Boolean).join(' • ')||'Perangkat tidak dikenali'}</span><span>{[row.os,row.os_version].filter(Boolean).join(' ')||'OS tidak diketahui'} • {[row.browser,row.browser_version].filter(Boolean).join(' ')||'Browser tidak diketahui'}</span><span><Globe2 size={13} className="mr-1 inline"/>{row.ip_address||'IP tidak tersedia'}{row.client_timezone?` • ${row.client_timezone}`:''}</span></div></div></div></Card>)}</div>}</div>;}
