import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Clock3, MapPin, ShieldAlert } from 'lucide-react';
import Card from '../components/ui/Card';
import Badge from '../components/ui/Badge';
import { useAuth } from '../context/AuthContext';
import { supabase } from '../lib/supabase';

interface Row { id:string; scheduled_time:string|null; actual_arrival:string|null; status:string; delay_minutes:number; confidence:number|null; evidence:string|null; created_at:string; }
const statusLabel:Record<string,string>={on_time:'Hadir tepat waktu',late:'Terlambat',not_arrived:'Belum tiba',location_unknown:'Lokasi tidak diketahui',manual_override:'Manual',cancelled:'Dibatalkan',scheduled:'Terjadwal'};
export default function Attendance(){const {user}=useAuth();const [rows,setRows]=useState<Row[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
useEffect(()=>{if(!user?.id)return;let live=true;setLoading(true);void supabase.from('attendance_logs').select('id,scheduled_time,actual_arrival,status,delay_minutes,confidence,evidence,created_at').eq('user_id',user.id).order('scheduled_time',{ascending:false}).limit(100).then(({data,error})=>{if(!live)return;if(error)setError(error.message);setRows((data??[]) as Row[]);setLoading(false)});return()=>{live=false}},[user?.id]);
const stats=useMemo(()=>({onTime:rows.filter(x=>x.status==='on_time').length,late:rows.filter(x=>x.status==='late').length,unknown:rows.filter(x=>x.status==='location_unknown').length}),[rows]);
return <div className="space-y-5 fade-up"><div><h1 className="text-2xl font-extrabold tracking-tight">Attendance & Routine</h1><p className="mt-1 text-sm text-slate-500">Riwayat kehadiran berbasis data lokasi yang telah diizinkan pengguna; tidak ada tracking tanpa permission.</p></div><div className="grid gap-3 sm:grid-cols-3"><Card className="p-4"><div className="text-xs font-bold uppercase tracking-wider text-slate-400">Tepat waktu</div><div className="mt-1 text-3xl font-black">{stats.onTime}</div></Card><Card className="p-4"><div className="text-xs font-bold uppercase tracking-wider text-slate-400">Terlambat</div><div className="mt-1 text-3xl font-black">{stats.late}</div></Card><Card className="p-4"><div className="text-xs font-bold uppercase tracking-wider text-slate-400">Lokasi tidak pasti</div><div className="mt-1 text-3xl font-black">{stats.unknown}</div></Card></div><Card className="overflow-hidden"><div className="flex items-center gap-2 border-b border-slate-100 px-4 py-4 dark:border-slate-800"><MapPin size={18} className="text-blue-600"/><h2 className="font-bold">Riwayat Attendance</h2></div>{error&&<div className="m-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}{loading?<div className="p-5 text-sm text-slate-400">Memuat data…</div>:rows.length===0?<div className="p-8 text-center text-sm text-slate-400"><ShieldAlert className="mx-auto mb-2" size={22}/><div>Belum ada data attendance yang tersimpan.</div></div>:<div className="divide-y divide-slate-100 dark:divide-slate-800">{rows.map((row)=><div key={row.id} className="flex flex-col gap-2 p-4 sm:flex-row sm:items-center"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-slate-100 dark:bg-slate-900"><CheckCircle2 size={17}/></div><div className="min-w-0 flex-1"><div className="font-bold">{statusLabel[row.status]??row.status}</div><div className="mt-1 text-xs text-slate-500">{row.scheduled_time?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(row.scheduled_time)):'Waktu tidak tersedia'}{row.actual_arrival?` • tiba ${new Intl.DateTimeFormat('id-ID',{timeStyle:'short'}).format(new Date(row.actual_arrival))}`:''}</div></div><div className="flex items-center gap-2">{row.delay_minutes>0?<Badge tone="amber">+{row.delay_minutes} menit</Badge>:<Badge tone="green">On time</Badge>}{row.confidence!=null&&<Badge tone="slate">{Math.round(row.confidence*100)}%</Badge>}</div></div>)}</div>}</Card><Card className="p-4"><div className="flex items-center gap-2 font-bold"><Clock3 size={17} className="text-indigo-600"/> Privasi lokasi</div><p className="mt-2 text-sm leading-6 text-slate-500">Location Intelligence tetap opt-in. Browser dapat membatasi background GPS; data hanya berguna ketika permission diberikan dan perangkat mengirim pembacaan.</p></Card></div>}
