import { useState } from 'react';
import type { ComponentType, ReactNode } from 'react';
import { Search as SearchIcon, ClipboardList, Users, CalendarClock, Megaphone } from 'lucide-react';
import Card from '../components/ui/Card';
import EmptyState from '../components/ui/EmptyState';
import { globalSearch } from '../services/searchService';
import { useNavigate } from 'react-router-dom';

export default function SearchPage(){
  const [term,setTerm]=useState(''); const [loading,setLoading]=useState(false); const [results,setResults]=useState<{tasks:any[];users:any[];schedule:any[];announcements:any[]}|null>(null); const nav=useNavigate();
  async function submit(e:React.FormEvent){e.preventDefault();if(!term.trim())return;setLoading(true);try{setResults(await globalSearch(term))}finally{setLoading(false)}}
  return <div className="mx-auto max-w-6xl space-y-5 fade-up"><div><h1 className="text-2xl font-extrabold">Pencarian Global</h1><p className="mt-1 text-sm text-slate-500">Cari tugas, pengguna, jadwal, dan pengumuman dari satu tempat.</p></div><form onSubmit={submit} className="relative"><SearchIcon className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input autoFocus className="input h-12 pl-11 pr-28" value={term} onChange={e=>setTerm(e.target.value)} placeholder="Ketik kata kunci..."/><button disabled={loading} className="absolute right-2 top-2 rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white">{loading?'Mencari…':'Cari'}</button></form>{results&&!Object.values(results).some(a=>a.length)&&<EmptyState title="Tidak ada hasil" description="Coba kata kunci lain."/>}{results&&<div className="grid gap-4 md:grid-cols-2">{section('Tugas',ClipboardList,results.tasks,(x:any)=><button key={x.id} className="w-full rounded-xl border border-slate-100 p-3 text-left hover:bg-slate-50" onClick={()=>nav(`/tasks/${x.id}`)}><div className="text-xs font-bold text-blue-600">{x.subject_name}</div><div className="mt-1 text-sm font-bold">{x.title}</div><div className="mt-1 text-xs text-slate-500">{x.due_date} • {x.due_time}</div></button>)}{section('Users',UsersIcon,results.users,(x:any)=><div key={x.id} className="rounded-xl border border-slate-100 p-3"><div className="text-sm font-bold">{x.name}</div><div className="text-xs text-slate-500">{x.email} • {x.role}</div></div>)}{section('Jadwal',CalendarClock,results.schedule,(x:any)=><div key={x.id} className="rounded-xl border border-slate-100 p-3"><div className="text-sm font-bold">{x.subject}</div><div className="text-xs text-slate-500">{x.day} • {String(x.start_time).slice(0,5)}–{String(x.end_time).slice(0,5)} • {x.teacher||'—'}</div></div>)}{section('Pengumuman',Megaphone,results.announcements,(x:any)=><div key={x.id} className="rounded-xl border border-slate-100 p-3"><div className="text-sm font-bold">{x.title}</div><div className="mt-1 line-clamp-2 text-xs text-slate-500">{x.body}</div></div>)}</div>}</div>
}
function section(title:string,Icon:ComponentType<{size?:number}>,items:any[],render:(x:any)=>ReactNode){return <Card className="p-4" key={title}><div className="mb-3 flex items-center gap-2"><Icon size={17}/><h2 className="font-bold">{title}</h2><span className="ml-auto rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-bold">{items.length}</span></div><div className="space-y-2">{items.slice(0,6).map(render)}</div></Card>}
function UsersIcon({size=17}:{size?:number}){return <Users size={size}/>}
