import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CalendarClock, Check, CheckCircle2, Download, Edit3, FileText, MessageSquare, Plus, Trash2 } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { getTask, updateTask, removeTask, completeTask } from '../services/taskService';
import { addComment, addSubtask, deleteComment, deleteSubtask, listComments, listSubtasks, toggleSubtask, type TaskComment, type TaskSubtask } from '../services/taskWorkspaceService';
import { subscribeToPostgresChanges } from '../lib/realtime';
import { useAuth } from '../context/AuthContext';
import type { Task } from '../types';
import Card from '../components/ui/Card';
import Button from '../components/ui/Button';
import Badge from '../components/ui/Badge';
import { PriorityBadge, StatusBadge } from '../components/ui/StatusBadge';
import Modal from '../components/ui/Modal';
import TaskForm from '../components/tasks/TaskForm';
import { formatDate, relativeDeadline, errorMessage } from '../lib/utils';

export default function TaskDetail(){
  const {id}=useParams(); const nav=useNavigate(); const {user,profile,isAdmin}=useAuth();
  const [task,setTask]=useState<Task|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [edit,setEdit]=useState(false); const [confirm,setConfirm]=useState(false); const [remaining,setRemaining]=useState(0);
  const [subtasks,setSubtasks]=useState<TaskSubtask[]>([]); const [comments,setComments]=useState<TaskComment[]>([]); const [subtaskText,setSubtaskText]=useState(''); const [commentText,setCommentText]=useState('');
  useEffect(()=>{if(!id)return;setLoading(true);getTask(id).then(setTask).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false));},[id]);
  useEffect(()=>{if(!task)return;const target=new Date(`${task.dueDate}T${task.dueTime}`).getTime();setRemaining(Math.max(0,target-Date.now()));const t=setInterval(()=>setRemaining(Math.max(0,target-Date.now())),1000);return()=>clearInterval(t)},[task]);
  const loadWorkspace=()=>{if(!task)return;void Promise.all([listSubtasks(task.id),listComments(task.id)]).then(([s,c])=>{setSubtasks(s);setComments(c)}).catch(()=>undefined)};
  useEffect(()=>{loadWorkspace();if(!task)return;const a=subscribeToPostgresChanges({topic:`task-detail-subtasks:${task.id}`,table:'task_subtasks',filter:`task_id=eq.${task.id}`,onChange:loadWorkspace,onError:()=>undefined});const b=subscribeToPostgresChanges({topic:`task-detail-comments:${task.id}`,table:'task_comments',filter:`task_id=eq.${task.id}`,onChange:loadWorkspace,onError:()=>undefined});return()=>{a();b()}},[task?.id]);
  const owner=task?.assignedTo===user?.id||task?.createdBy===user?.id||isAdmin; const countdown=useMemo(()=>{const d=Math.floor(remaining/86400000);const h=Math.floor((remaining%86400000)/3600000);const m=Math.floor((remaining%3600000)/60000);const s=Math.floor((remaining%60000)/1000);return {d,h,m,s}},[remaining]);
  async function del(){if(!task)return;try{await removeTask(task.id);nav('/tasks')}catch(e){setError(errorMessage(e))}finally{setConfirm(false)}}
  async function complete(){if(!task)return;try{await completeTask(task.id);setTask(await getTask(task.id))}catch(e){setError(errorMessage(e))}}
  async function addNewSubtask(){if(!task||!user||!subtaskText.trim())return;try{await addSubtask(task.id,user.id,subtaskText,subtasks.length);setSubtaskText('');loadWorkspace()}catch(e){setError(errorMessage(e))}}
  async function addNewComment(){if(!task||!user||!profile||!commentText.trim())return;try{await addComment(task.id,user.id,profile.name,commentText);setCommentText('');loadWorkspace()}catch(e){setError(errorMessage(e))}}
  if(loading)return <div className="space-y-4"><div className="h-8 w-40 animate-pulse rounded bg-slate-200"/><div className="h-96 animate-pulse rounded-2xl bg-slate-200"/></div>;
  if(error||!task)return <Card className="p-10 text-center"><h2 className="font-bold">{error||'Tugas tidak ditemukan'}</h2><Button className="mt-4" variant="outline" onClick={()=>nav('/tasks')}>Kembali</Button></Card>;
  return <div className="space-y-5 fade-up"><button onClick={()=>nav('/tasks')} className="focus-ring inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-slate-900"><ArrowLeft size={16}/> Kembali ke tugas</button>
    {error&&<div className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
    <div className="grid gap-5 xl:grid-cols-[1fr_360px]">
      <div className="space-y-5"><Card className="p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-extrabold uppercase tracking-wider text-blue-600">{task.subjectName}</span><PriorityBadge priority={task.priority}/><StatusBadge status={task.status}/>{task.tags?.map(tag=><Badge key={tag} tone="slate">#{tag}</Badge>)}</div><h1 className="mt-3 text-3xl font-black tracking-tight">{task.title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">Guru: {task.teacherName} • Dibuat oleh {task.createdByName}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" icon={<Edit3 size={15}/>} disabled={!owner} onClick={()=>setEdit(true)}>Edit</Button><Button variant="danger" size="sm" icon={<Trash2 size={15}/>} disabled={!owner} onClick={()=>setConfirm(true)}>Hapus</Button></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-semibold text-slate-400">Deadline</div><div className="mt-1 font-bold">{formatDate(task.dueDate)} • {task.dueTime}</div><div className="mt-1 text-xs font-semibold text-blue-600">{relativeDeadline(task)}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-semibold text-slate-400">Countdown</div><div className="mt-1 font-bold">{remaining>0?`${countdown.d}h ${countdown.h}j ${String(countdown.m).padStart(2,'0')}m`: 'Deadline lewat'}</div><div className="mt-1 text-xs text-slate-400">{remaining>0?`${countdown.s} detik`: 'Perbarui status bila diperlukan'}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-semibold text-slate-400">Pengumpulan</div><div className="mt-2"><Badge tone={task.submissionStatus==='submitted'?'green':'slate'}>{task.submissionStatus||'not_submitted'}</Badge></div></div></div><div className="mt-7 border-t border-slate-100 pt-6"><h2 className="font-bold">Deskripsi</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-slate-600">{task.description||'Tidak ada deskripsi.'}</p></div>{task.notes&&<div className="mt-6"><h2 className="font-bold">Catatan</h2><p className="mt-2 whitespace-pre-wrap rounded-2xl bg-amber-50 p-4 text-sm leading-6 text-amber-900">{task.notes}</p></div>}</Card>
        <Card className="p-5"><div className="flex items-center gap-2"><CheckCircle2 size={18} className="text-blue-600"/><h2 className="font-bold">Checklist tugas</h2><span className="ml-auto text-xs font-semibold text-slate-400">{subtasks.filter(s=>s.done).length}/{subtasks.length}</span></div><div className="mt-3 flex gap-2"><input className="input" value={subtaskText} onChange={e=>setSubtaskText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void addNewSubtask()}} placeholder="Tambah langkah kecil..."/><Button onClick={()=>void addNewSubtask()} icon={<Plus size={15}/>}>Tambah</Button></div><div className="mt-4 space-y-2">{subtasks.length===0?<div className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Belum ada checklist. Pecah tugas menjadi langkah kecil agar lebih mudah diselesaikan.</div>:subtasks.map(s=><div key={s.id} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><button onClick={()=>void toggleSubtask(s.id,!s.done)} className={`grid h-6 w-6 place-items-center rounded-lg border ${s.done?'border-emerald-500 bg-emerald-500 text-white':'border-slate-300 text-transparent'}`} aria-label="Toggle checklist"><Check size={14}/></button><span className={`flex-1 text-sm ${s.done?'text-slate-400 line-through':'font-medium text-slate-700'}`}>{s.title}</span><button onClick={()=>void deleteSubtask(s.id)} className="rounded-lg p-1.5 text-slate-400 hover:bg-rose-50 hover:text-rose-600" aria-label="Hapus checklist"><Trash2 size={14}/></button></div>)}</div></Card>
        <Card className="p-5"><div className="flex items-center gap-2"><MessageSquare size={18} className="text-blue-600"/><h2 className="font-bold">Diskusi tugas</h2><span className="ml-auto text-xs font-semibold text-slate-400">{comments.length} komentar</span></div><div className="mt-4 space-y-3">{comments.map(c=><div key={c.id} className="rounded-xl border border-slate-100 p-3"><div className="flex items-center justify-between"><div className="text-xs font-bold">{c.userName}</div>{c.userId===user?.id||isAdmin?<button onClick={()=>void deleteComment(c.id)} className="text-slate-400 hover:text-rose-600"><Trash2 size={13}/></button>:null}</div><div className="mt-1 whitespace-pre-wrap text-sm text-slate-600">{c.body}</div></div>)}{comments.length===0&&<div className="text-sm text-slate-500">Belum ada diskusi.</div>}</div><div className="mt-4 flex gap-2"><textarea className="input min-h-16" value={commentText} onChange={e=>setCommentText(e.target.value)} placeholder="Tulis komentar, pertanyaan, atau catatan..."/><Button onClick={()=>void addNewComment()}>Kirim</Button></div></Card></div>
      <div className="space-y-4"><Card className="p-5"><div className="mb-4 flex items-center gap-2"><FileText size={18} className="text-blue-600"/><h2 className="font-bold">File Tugas</h2></div>{task.fileUrl?<a href={task.fileUrl} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 hover:bg-slate-50"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><FileText size={18}/></div><div className="min-w-0 flex-1"><div className="truncate text-sm font-bold">{task.fileName}</div><div className="text-xs text-slate-400">{task.fileType}</div></div><Download size={16}/></a>:<div className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Belum ada file.</div>}</Card><Card className="p-5"><div className="mb-4 flex items-center gap-2"><CalendarClock size={18} className="text-blue-600"/><h2 className="font-bold">Aksi cepat</h2></div><Button disabled={!owner||task.status==='completed'} onClick={()=>void complete()} className="w-full" icon={<CheckCircle2 size={16}/>}>
        {task.status==='completed'?'Sudah selesai':'Tandai selesai'}</Button>{task.status!=='completed'&&task.status!=='submitted'&&<Button variant="outline" className="mt-2 w-full" onClick={()=>void updateTask(task.id,{status:'submitted',submissionStatus:'submitted'}).then(()=>getTask(task.id)).then(setTask)} >Tandai dikumpulkan</Button>}<div className="mt-3 text-xs leading-5 text-slate-400">Status overdue dihitung dari deadline dan status tugas aktif.</div></Card></div>
    </div>
    <TaskForm open={edit} initial={task} onClose={()=>setEdit(false)} onSaved={async()=>setTask(await getTask(task.id))}/><Modal open={confirm} onClose={()=>setConfirm(false)} title="Hapus tugas?"><p className="text-sm leading-6 text-slate-500">Tugas yang dihapus tidak dapat dipulihkan.</p><div className="mt-5 flex justify-end gap-2"><Button variant="ghost" onClick={()=>setConfirm(false)}>Batal</Button><Button variant="danger" onClick={()=>void del()}>Hapus</Button></div></Modal>
  </div>
}
