import { useEffect, useState } from 'react';
import { Save, ShieldCheck, UserCircle } from 'lucide-react';
import Card from '../components/ui/Card';
import Button from '../components/ui/Button';
import Badge from '../components/ui/Badge';
import { useAuth } from '../context/AuthContext';
import { updateUserProfile } from '../services/userService';
import { errorMessage, formatDateTime } from '../lib/utils';
export default function Profile(){const {user,profile}=useAuth();const [name,setName]=useState('');const [photoURL,setPhotoURL]=useState('');const [loading,setLoading]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');useEffect(()=>{setName(profile?.name||'');setPhotoURL(profile?.photoURL||'')},[profile]);async function save(){if(!user)return;setLoading(true);setMessage('');setError('');try{let url=photoURL;await updateUserProfile(user.id,{name:name.trim(),photoURL:url});setMessage('Profil berhasil diperbarui.');}catch(err){setError(err instanceof Error?err.message:errorMessage(err))}finally{setLoading(false)}}return <div className="mx-auto max-w-2xl space-y-5 fade-up"><div><h1 className="text-2xl font-extrabold">Profil</h1><p className="mt-1 text-sm text-slate-500">Data profil disimpan di Supabase Postgres dan tersinkron lintas perangkat.</p></div><Card className="p-5"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="relative"><div className="grid h-24 w-24 place-items-center overflow-hidden rounded-3xl bg-blue-100 text-2xl font-black text-blue-700">{photoURL?<img src={photoURL} alt="Foto profil" className="h-full w-full object-cover"/>:<UserCircle size={44}/>}</div></div><div><h2 className="font-bold">{profile?.name||'Pengguna'}</h2><p className="text-sm text-slate-500">{profile?.email}</p><div className="mt-2"><Badge tone={profile?.role==='admin'?'purple':'blue'}>{profile?.role==='admin'?'Administrator':'Siswa'}</Badge></div></div></div></Card><Card className="p-5"><div className="grid gap-4"><label><span className="label">Nama</span><input className="input" value={name} onChange={e=>setName(e.target.value)} required/></label><label><span className="label">Email</span><input className="input bg-slate-50" value={profile?.email||''} disabled/></label><div className="grid gap-4 sm:grid-cols-2"><div><div className="label">Akun dibuat</div><div className="text-sm font-semibold text-slate-700">{formatDateTime(profile?.createdAt)}</div></div><div><div className="label">Login terakhir</div><div className="text-sm font-semibold text-slate-700">{formatDateTime(profile?.lastLoginAt)}</div></div></div>{message&&<div className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{message}</div>}{error&&<div className="rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700">{error}</div>}<div className="flex justify-end"><Button loading={loading} onClick={save} icon={<Save size={16}/>}>Simpan Perubahan</Button></div></div></Card><Card className="p-5"><div className="flex gap-3"><ShieldCheck className="mt-0.5 text-emerald-600" size={20}/><div><h3 className="font-bold">Security</h3><p className="mt-1 text-sm leading-6 text-slate-500">Role dan izin tidak ditentukan dari UI. Akses admin divalidasi oleh Supabase Custom Claims dan Security Rules.</p></div></div></Card></div>}
