import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const root=dirname(fileURLToPath(import.meta.url));const env=readFileSync(join(root,'..','.env'),'utf8');
function envGet(k:string){return env.match(new RegExp(`^${k}=(.*)$`,'m'))?.[1]?.trim().replace(/^['"]|['"]$/g,'')??process.env[k]}
const url=process.env.SUPABASE_URL||envGet('VITE_SUPABASE_URL');const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.');
const db=createClient(url,key,{auth:{persistSession:false}});
const days:any[]=[
{day:'Senin',slots:[['07:00','07:45','UPACARA','', 'ceremony'],['07:45','08:30','BAHASA INGGRIS','ENDAH LISTYANI','subject'],['08:30','09:15','BAHASA INGGRIS','ENDAH LISTYANI','subject'],['09:15','10:00','BAHASA INGGRIS','ENDAH LISTYANI','subject'],['10:00','10:15','ISTIRAHAT','','break'],['10:15','11:00','MATEMATIKA','INDAYATI','subject'],['11:00','11:45','MATEMATIKA','INDAYATI','subject'],['11:45','12:30','ISTIRAHAT SHOLAT MAKAN','','religious_break'],['12:30','13:10','BAHASA INDONESIA',"EVY AFIATU SA'ADA",'subject'],['13:10','13:50','BAHASA INDONESIA',"EVY AFIATU SA'ADA",'subject'],['13:50','14:30','BAHASA JAWA','PUTRI WAHYU PRAMUDITA, S.Pd.','subject'],['14:30','15:10','BAHASA JAWA','PUTRI WAHYU PRAMUDITA, S.Pd.','subject'],['15:10','15:20','ASRI','','school_activity']]},
{day:'Selasa',slots:[['07:00','07:45','PAI','MUH MISBAKHUL MUNIR','subject'],['07:45','08:30','PAI','MUH MISBAKHUL MUNIR','subject'],['08:30','09:15','PAI','MUH MISBAKHUL MUNIR','subject'],['09:15','10:00','BHS INGGRIS TINGKAT LANJUT','ROPIKOHERNA C','subject'],['10:00','10:15','ISTIRAHAT','','break'],['10:15','11:00','BHS INGGRIS TINGKAT LANJUT','ROPIKOHERNA C','subject'],['11:00','11:45','BK','YAYUK KASMAWATI','subject'],['11:45','12:30','ISTIRAHAT SHOLAT MAKAN','','religious_break'],['12:30','13:10','MATEMATIKA TINGKAT LANJUT','SUKISNAWATI, S.Pd','subject'],['13:10','13:50','MATEMATIKA TINGKAT LANJUT','SUKISNAWATI, S.Pd','subject'],['13:50','14:30','SENI DAN BUDAYA','METARANY JUANG M, S.Sn','subject'],['14:30','15:10','SENI DAN BUDAYA','METARANY JUANG M, S.Sn','subject'],['15:10','15:20','ASRI','','school_activity']]},
{day:'Rabu',slots:[['07:00','07:45','PENJASKES','EDI PURWANTO','subject'],['07:45','08:30','PENJASKES','EDI PURWANTO','subject'],['08:30','09:15','PENJASKES','EDI PURWANTO','subject'],['09:15','10:00','INFORMATIKA','ZAKARIA MUTTAQIN','subject'],['10:00','10:15','ISTIRAHAT','','break'],['10:15','11:00','INFORMATIKA','ZAKARIA MUTTAQIN','subject'],['11:00','11:45','INFORMATIKA','ZAKARIA MUTTAQIN','subject'],['11:45','12:30','ISTIRAHAT SHOLAT MAKAN','','religious_break'],['12:30','13:10','MATEMATIKA','INDAYATI','subject'],['13:10','13:50','MATEMATIKA','INDAYATI','subject'],['13:50','14:30','PRAKARYA','PUJI RAHAYU, S.Pd','subject'],['14:30','15:10','PRAKARYA','PUJI RAHAYU, S.Pd','subject'],['15:10','15:20','ASRI','','school_activity']]},
{day:'Kamis',slots:[['07:00','07:45','BHS INGGRIS TINGKAT LANJUT','ROPIKOHERNA C','subject'],['07:45','08:30','BHS INGGRIS TINGKAT LANJUT','ROPIKOHERNA C','subject'],['08:30','09:15','BHS INGGRIS TINGKAT LANJUT','ROPIKOHERNA C','subject'],['09:15','10:00','SEJARAH','AGUS SUGIANTO','subject'],['10:00','10:15','ISTIRAHAT','','break'],['10:15','11:00','SEJARAH','AGUS SUGIANTO','subject'],['11:00','11:45','MATEMATIKA TINGKAT LANJUT','SUKISNAWATI, S.Pd','subject'],['11:45','12:30','ISTIRAHAT SHOLAT MAKAN','','religious_break'],['12:30','13:10','MATEMATIKA TINGKAT LANJUT','SUKISNAWATI, S.Pd','subject'],['13:10','13:50','MATEMATIKA TINGKAT LANJUT','SUKISNAWATI, S.Pd','subject'],['13:50','14:30','FISIKA','SUTJI RAHAYU','subject'],['14:30','15:10','FISIKA','SUTJI RAHAYU','subject'],['15:10','15:20','ASRI','','school_activity']]},
{day:'Jumat',slots:[['07:00','07:45','PPKN','BAMBANG PURNOMO','subject'],['07:45','08:30','PPKN','BAMBANG PURNOMO','subject'],['08:30','09:15','BAHASA INDONESIA',"EVY AFIATU SA'ADA",'subject'],['09:15','10:00','BAHASA INDONESIA',"EVY AFIATU SA'ADA",'subject'],['10:00','10:15','ISTIRAHAT','','break'],['10:15','11:00','FISIKA','SUTJI RAHAYU','subject'],['11:00','11:30','FISIKA','SUTJI RAHAYU','subject'],['11:30','13:00','SHOLAT JUMAT MAKAN ISTIRAHAT','','religious_break'],['13:00','13:40','FISIKA','SUTJI RAHAYU','subject'],['13:40','14:20','INFORMATIKA','ZAKARIA MUTTAQIN','subject'],['14:20','15:00','INFORMATIKA','ZAKARIA MUTTAQIN','subject'],['15:00','15:10','ASRI','','school_activity']]}
];
const run=async()=>{const {count}=await db.from('schedule').select('id',{count:'exact',head:true});if((count??0)>0){console.log(`Schedule already contains ${count} rows; seed skipped.`);return;}const subjects=new Map<string,string>();const rows:any[]=[];days.forEach((d,di)=>d.slots.forEach((s:any)=>{if(s[4]==='subject')subjects.set(s[2],s[3]);rows.push({day:d.day,day_order:di,start_time:s[0],end_time:s[1],subject:s[2],teacher:s[3]||null,type:s[4],active:true})}));if(subjects.size){const subRows=[...subjects].map(([name,teacher])=>({name,teacher,active:true}));const {error}=await db.from('subjects').upsert(subRows,{onConflict:'name'});if(error)throw error;}const {error}=await db.from('schedule').insert(rows);if(error)throw error;console.log(`Seeded ${rows.length} schedule rows and ${subjects.size} subjects.`)};run().catch(e=>{console.error(e);process.exit(1)})
