import { useState } from 'react';
import { Eye, EyeOff, LockKeyhole, Mail, GraduationCap, ArrowRight } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import Button from '../components/ui/Button';
import { useAuth } from '../context/AuthContext';
import { errorMessage } from '../lib/utils';
export default function Login(){const {login}=useAuth();const nav=useNavigate();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [remember,setRemember]=useState(true);const [show,setShow]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');async function submit(e:React.FormEvent){e.preventDefault();setError('');setLoading(true);try{await login(email.trim(),password,remember);nav('/dashboard',{replace:true});}catch(err){setError(errorMessage(err));}finally{setLoading(false)}}return <AuthLayout eyebrow="Welcome back"><div className="mb-8"><div className="mb-4 grid h-12 w-12 place-items-center rounded-2xl bg-blue-600 text-white shadow-lg shadow-blue-600/20"><GraduationCap size={24}/></div><h1 className="text-3xl font-extrabold tracking-tight text-slate-950">Masuk ke Taskflow</h1><p className="mt-2 text-sm leading-6 text-slate-500">Kelola tugas, jadwal, dan progres sekolahmu dalam satu tempat.</p></div><form onSubmit={submit} className="space-y-4"><Field icon={<Mail size={16}/>} label="Email"><input className="input pl-10" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="nama@sekolah.sch.id"/></Field><Field icon={<LockKeyhole size={16}/>} label="Password"><div className="relative"><input className="input px-10 pr-11" type={show?'text':'password'} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required placeholder="••••••••"/><button type="button" aria-label={show?'Sembunyikan password':'Tampilkan password'} className="focus-ring absolute right-2 top-1/2 -translate-y-1/2 rounded-lg p-2 text-slate-400" onClick={()=>setShow(!show)}>{show?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></Field>{error&&<div role="alert" className="rounded-xl border border-rose-100 bg-rose-50 px-3 py-2.5 text-sm font-semibold text-rose-700">{error}</div>}<label className="flex items-center gap-2 text-sm font-semibold text-slate-600"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)} className="h-4 w-4 rounded border-slate-300"/>Remember Me</label><Button type="submit" loading={loading} className="w-full" size="lg" icon={<ArrowRight size={17}/>}>Login</Button><div className="flex items-center justify-between text-sm"><Link className="font-semibold text-blue-600 hover:text-blue-700" to="/forgot-password">Lupa password?</Link><span className="text-slate-400">Belum punya akun? <Link className="font-semibold text-blue-600" to="/register">Daftar</Link></span></div></form></AuthLayout>}
function Field({label,icon,children}:{label:string;icon:React.ReactNode;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-bold uppercase tracking-wider text-slate-500">{label}</span><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400">{icon}</span>{children}</div></label>}
export function AuthLayout({children,eyebrow}:{children:React.ReactNode;eyebrow:string}){return <div className="min-h-screen bg-slate-950 lg:grid lg:grid-cols-[1.1fr_.9fr]"><div className="relative hidden overflow-hidden p-12 lg:flex lg:flex-col lg:justify-between"><div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_20%,rgba(59,130,246,.22),transparent_30%),radial-gradient(circle_at_80%_80%,rgba(14,165,233,.14),transparent_35%)]"/><div className="relative"><div className="flex items-center gap-3 text-white"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-600"><GraduationCap size={21}/></div><div className="font-extrabold tracking-tight">TASKFLOW <span className="text-blue-300">SCHOOL</span></div></div><div className="mt-28 max-w-xl"><div className="mb-5 inline-flex rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs font-bold text-blue-200">{eyebrow}</div><h2 className="text-5xl font-black leading-tight tracking-tight text-white">School productivity, <span className="text-blue-300">lebih terarah.</span></h2><p className="mt-5 max-w-lg text-base leading-7 text-slate-300">Satu workspace untuk tugas, jadwal, deadline, notifikasi, dan insight belajar yang sinkron lintas perangkat.</p></div></div><div className="relative text-xs text-slate-500">Data disimpan di Supabase • Secure by design</div></div><div className="flex items-center bg-slate-50 p-5 sm:p-8"><div className="mx-auto w-full max-w-md"><div className="mb-8 text-xs font-semibold uppercase tracking-widest text-slate-400 lg:hidden">TASKFLOW SCHOOL</div>{children}</div></div></div>}
