import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { User, Mail, LockKeyhole, GraduationCap } from 'lucide-react';
import Button from '../components/ui/Button';
import { useAuth } from '../context/AuthContext';
import { errorMessage } from '../lib/utils';
import { AuthLayout } from './Login';
export default function Register(){const {register}=useAuth();const nav=useNavigate();const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');async function submit(e:React.FormEvent){e.preventDefault();if(password!==confirm){setError('Konfirmasi password tidak sama.');return}setError('');setLoading(true);try{await register(name.trim(),email.trim(),password);nav('/dashboard',{replace:true});}catch(err){setError(errorMessage(err));}finally{setLoading(false)}}return <AuthLayout eyebrow="Create your account"><div className="mb-8"><div className="mb-4 grid h-12 w-12 place-items-center rounded-2xl bg-blue-600 text-white"><GraduationCap size={24}/></div><h1 className="text-3xl font-extrabold tracking-tight">Buat akun siswa</h1><p className="mt-2 text-sm text-slate-500">Mulai dari akunmu sendiri. Role default adalah user.</p></div><form onSubmit={submit} className="space-y-4"><Field label="Nama lengkap" icon={<User size={16}/>}><input className="input pl-10" value={name} onChange={e=>setName(e.target.value)} required/></Field><Field label="Email" icon={<Mail size={16}/>}><input className="input pl-10" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></Field><Field label="Password" icon={<LockKeyhole size={16}/>}><input className="input pl-10" type="password" autoComplete="new-password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} required/></Field><Field label="Konfirmasi password" icon={<LockKeyhole size={16}/>}><input className="input pl-10" type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} required/></Field>{error&&<div role="alert" className="rounded-xl border border-rose-100 bg-rose-50 px-3 py-2.5 text-sm font-semibold text-rose-700">{error}</div>}<Button type="submit" loading={loading} className="w-full" size="lg">Daftar</Button><div className="text-center text-sm text-slate-500">Sudah punya akun? <Link className="font-semibold text-blue-600" to="/login">Masuk</Link></div></form></AuthLayout>}
function Field({label,icon,children}:{label:string;icon:React.ReactNode;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-bold uppercase tracking-wider text-slate-500">{label}</span><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400">{icon}</span>{children}</div></label>}
