import { useEffect, useMemo, useState } from 'react';
import { Download, RefreshCw, Search, Table2 } from 'lucide-react';
import AdminHeader from '../../components/admin/AdminHeader';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import { supabase } from '../../lib/supabase';
import { errorMessage } from '../../lib/utils';

const TABLES = ['users','tasks','schedule','subjects','teachers','notifications','announcements','login_sessions','audit_logs'] as const;
type TableName = typeof TABLES[number];
export default function AdminData(){ const [table,setTable]=useState<TableName>('users'); const [rows,setRows]=useState<Record<string,unknown>[]>([]); const [query,setQuery]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=async()=>{setLoading(true);setError('');const {data,error}=await supabase.from(table).select('*').limit(250);if(error){setError(errorMessage(error));setRows([]);}else setRows((data??[]) as Record<string,unknown>[]);setLoading(false);}; useEffect(()=>{void load()},[table]);
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return rows;return rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q))},[rows,query]);
  const columns=useMemo(()=>{const set=new Set<string>();rows.slice(0,40).forEach(r=>Object.keys(r).forEach(k=>set.add(k)));return [...set].slice(0,10)},[rows]);
  const exportCsv=()=>{const header=columns.join(',');const lines=filtered.map(r=>columns.map(c=>JSON.stringify(r[c]??'')).join(','));const blob=new Blob([[header,...lines].join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${table}-export.csv`;a.click();URL.revokeObjectURL(url);};
  return <div className="space-y-6 fade-up"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><AdminHeader title="Data Workspace" description="Satu tempat untuk melihat data inti aplikasi dan mengekspornya."/><div className="flex flex-wrap gap-2"><select className="input w-48" value={table} onChange={e=>setTable(e.target.value as TableName)}>{TABLES.map(t=><option key={t}>{t}</option>)}</select><Button variant="outline" onClick={()=>void load()} icon={<RefreshCw size={15}/>}>Refresh</Button><Button variant="outline" onClick={exportCsv} icon={<Download size={15}/>}>CSV</Button></div></div><Card className="p-4"><div className="relative max-w-lg"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="input pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter isi data..."/></div></Card>{error&&<Card className="border-rose-200 p-4 text-sm font-semibold text-rose-700">{error}</Card>}<Card className="overflow-hidden"><div className="flex items-center gap-2 border-b border-slate-100 px-4 py-3 text-xs text-slate-500 dark:border-slate-800"><Table2 size={15}/> {table} • {filtered.length} rows</div><div className="overflow-auto"><table className="min-w-[900px] w-full text-left text-xs"><thead className="bg-slate-50 dark:bg-slate-900"><tr>{columns.map(c=><th key={c} className="px-3 py-2 font-bold">{c}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{loading?<tr><td colSpan={columns.length||1} className="p-8 text-center text-slate-500">Loading…</td></tr>:filtered.map((r,i)=><tr key={String(r.id??i)}>{columns.map(c=><td key={c} className="max-w-64 truncate px-3 py-2 align-top">{typeof r[c]==='object'?JSON.stringify(r[c]):String(r[c]??'')}</td>)}</tr>)}</tbody></table></div></Card></div>; }
